## Numpy Operation

In [1]:
import numpy as np

In [2]:
arr1 = np.zeros((3, 4))
arr2 = np.ones((3, 4))

In [3]:
arr1 + arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
arr1 = np.random.rand(3, 4)
arr2 = np.random.rand(3, 4)

In [5]:
arr1

array([[0.68925449, 0.18766587, 0.80586389, 0.32514831],
       [0.38480008, 0.0742276 , 0.29709224, 0.81733533],
       [0.66564087, 0.40741203, 0.58676115, 0.07886019]])

In [6]:
arr2

array([[0.39579594, 0.87307358, 0.34982626, 0.07753334],
       [0.46864619, 0.85064581, 0.20684075, 0.05279044],
       [0.91059051, 0.70301115, 0.73114348, 0.50439659]])

In [7]:
arr1 + arr2

array([[1.08505043, 1.06073945, 1.15569016, 0.40268165],
       [0.85344627, 0.92487342, 0.50393299, 0.87012577],
       [1.57623138, 1.11042318, 1.31790463, 0.58325678]])

In [8]:
arr1 - arr2

array([[ 0.29345855, -0.68540771,  0.45603763,  0.24761497],
       [-0.08384611, -0.77641821,  0.09025149,  0.76454489],
       [-0.24494964, -0.29559912, -0.14438233, -0.4255364 ]])

In [9]:
arr1 * arr2

array([[0.27280413, 0.16384611, 0.28191235, 0.02520983],
       [0.18033509, 0.0631414 , 0.06145078, 0.04314749],
       [0.60612626, 0.2864152 , 0.42900659, 0.03977681]])

In [10]:
arr1 / arr2

array([[ 1.74143902,  0.21494851,  2.30361175,  4.19365786],
       [ 0.82108868,  0.0872603 ,  1.43633325, 15.48263859],
       [ 0.73099913,  0.57952428,  0.80252532,  0.15634561]])

In [11]:
arr1 // arr2

array([[ 1.,  0.,  2.,  4.],
       [ 0.,  0.,  1., 15.],
       [ 0.,  0.,  0.,  0.]])

In [12]:
np.exp(arr1)

array([[1.99222976, 1.20643034, 2.2386296 , 1.38423592],
       [1.46932055, 1.07705192, 1.34593945, 2.26445776],
       [1.94573708, 1.50292323, 1.79815502, 1.08205303]])

In [13]:
np.log(arr1)

array([[-0.37214471, -1.67309219, -0.21584042, -1.12347387],
       [-0.95503135, -2.60061917, -1.21371261, -0.20170583],
       [-0.40700499, -0.89793025, -0.53313744, -2.54007871]])

In [14]:
np.log(np.exp(arr1))

array([[0.68925449, 0.18766587, 0.80586389, 0.32514831],
       [0.38480008, 0.0742276 , 0.29709224, 0.81733533],
       [0.66564087, 0.40741203, 0.58676115, 0.07886019]])

In [15]:
np.sin(arr1)

array([[0.63596204, 0.18656626, 0.72142915, 0.31944933],
       [0.37537384, 0.07415946, 0.29274107, 0.72932534],
       [0.61756332, 0.39623451, 0.55366682, 0.07877848]])

In [16]:
np.cos(arr1)

array([[0.77172034, 0.98244238, 0.69248826, 0.94760336],
       [0.9268735 , 0.9972464 , 0.95619175, 0.68416705],
       [0.78652117, 0.91814934, 0.83273829, 0.99689215]])

In [17]:
np.sqrt(arr1)

array([[0.83021352, 0.43320419, 0.89769922, 0.57021777],
       [0.62032256, 0.27244743, 0.54506169, 0.904066  ],
       [0.81586817, 0.63828836, 0.76600336, 0.28082057]])

In [18]:
arr_inv = 1 / arr1

In [19]:
arr_inv

array([[ 1.45084292,  5.32861944,  1.24090434,  3.07551961],
       [ 2.59875205, 13.47207691,  3.36595797,  1.22348804],
       [ 1.5023116 ,  2.45451761,  1.70427098, 12.68066898]])

In [20]:
arr1 = np.zeros((3, 5))

In [21]:
arr1_inv = 1 / arr1

c:\users\admin\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [22]:
print(arr1_inv)

[[inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]]


In [23]:
np.isinf(arr1_inv[0,0])

True

In [24]:
np.isinf(arr_inv)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])