## File Handling

In [1]:
import numpy as np

In [2]:
# planets_small = np.loadtxt("planets_small.txt")

In [3]:
# planets_small = np.loadtxt("planets_small.txt", skiprows = 1)

In [4]:
planets_small = np.loadtxt("planets_small.txt",skiprows = 1, usecols=(1,2,3,4,5,6,7,8,9))

In [5]:
planets_small

array([[3.3000e-01, 4.8700e+00, 5.9700e+00, 6.4200e-01, 1.8980e+03,
        5.6800e+02, 8.6800e+01, 1.0200e+02, 1.4600e-02],
       [5.7900e+01, 1.0820e+02, 1.4960e+02, 2.2790e+02, 7.7860e+02,
        1.4335e+03, 2.8725e+03, 4.4951e+03, 5.9064e+03],
       [4.2226e+03, 2.8020e+03, 2.4000e+01, 2.4700e+01, 9.9000e+00,
        1.0700e+01, 1.7200e+01, 1.6100e+01, 1.5330e+02]])

In [6]:
planets_small.shape

(3, 9)

In [7]:
# planets = np.loadtxt("planets.txt",skiprows = 1, usecols = (1,2,3,4,5,6,7,8,9))

In [8]:
planets = np.genfromtxt("planets.txt", skip_header=1, usecols=[1,2,3,4,5,6,7,8,9])

In [9]:
planets

array([[ 3.30000e-01,  4.87000e+00,  5.97000e+00,  7.30000e-02,
         6.42000e-01,  1.89800e+03,  5.68000e+02,  8.68000e+01,
         1.02000e+02],
       [ 4.87900e+03,  1.21040e+04,  1.27560e+04,  3.47500e+03,
         6.79200e+03,  1.42984e+05,  1.20536e+05,  5.11180e+04,
         4.95280e+04],
       [ 5.42700e+03,  5.24300e+03,  5.51400e+03,  3.34000e+03,
         3.93300e+03,  1.32600e+03,  6.87000e+02,  1.27100e+03,
         1.63800e+03],
       [ 3.70000e+00,  8.90000e+00,  9.80000e+00,  1.60000e+00,
         3.70000e+00,  2.31000e+01,  9.00000e+00,  8.70000e+00,
         1.10000e+01],
       [ 4.30000e+00,  1.04000e+01,  1.12000e+01,  2.40000e+00,
         5.00000e+00,  5.95000e+01,  3.55000e+01,  2.13000e+01,
         2.35000e+01],
       [ 1.40760e+03, -5.83250e+03,  2.39000e+01,  6.55700e+02,
         2.46000e+01,  9.90000e+00,  1.07000e+01, -1.72000e+01,
         1.61000e+01],
       [ 4.22260e+03,  2.80200e+03,  2.40000e+01,  7.08700e+02,
         2.47000e+01,  9.90000

In [10]:
planets.shape

(20, 9)

In [11]:
np.isnan(planets)

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, 

In [12]:
planets_new = np.nan_to_num(planets, nan=-1)

In [13]:
planets_new

array([[ 3.30000e-01,  4.87000e+00,  5.97000e+00,  7.30000e-02,
         6.42000e-01,  1.89800e+03,  5.68000e+02,  8.68000e+01,
         1.02000e+02],
       [ 4.87900e+03,  1.21040e+04,  1.27560e+04,  3.47500e+03,
         6.79200e+03,  1.42984e+05,  1.20536e+05,  5.11180e+04,
         4.95280e+04],
       [ 5.42700e+03,  5.24300e+03,  5.51400e+03,  3.34000e+03,
         3.93300e+03,  1.32600e+03,  6.87000e+02,  1.27100e+03,
         1.63800e+03],
       [ 3.70000e+00,  8.90000e+00,  9.80000e+00,  1.60000e+00,
         3.70000e+00,  2.31000e+01,  9.00000e+00,  8.70000e+00,
         1.10000e+01],
       [ 4.30000e+00,  1.04000e+01,  1.12000e+01,  2.40000e+00,
         5.00000e+00,  5.95000e+01,  3.55000e+01,  2.13000e+01,
         2.35000e+01],
       [ 1.40760e+03, -5.83250e+03,  2.39000e+01,  6.55700e+02,
         2.46000e+01,  9.90000e+00,  1.07000e+01, -1.72000e+01,
         1.61000e+01],
       [ 4.22260e+03,  2.80200e+03,  2.40000e+01,  7.08700e+02,
         2.47000e+01,  9.90000

In [14]:
np.savetxt('planets_new.txt', planets_new,delimiter = ',')

In [15]:
np.save("planets_new", planets_new)

In [16]:
!ls

'ls' is not recognized as an internal or external command,
operable program or batch file.


In [17]:
!ls -l

'ls' is not recognized as an internal or external command,
operable program or batch file.


In [18]:
!ls -lh

'ls' is not recognized as an internal or external command,
operable program or batch file.


In [19]:
arr1 = np.random.rand(1000,10)
arr2  = np.random.rand(2000,5)
arr3 = np.random.rand(20, 10000)

In [20]:
np.savez("many_arrs",arr1,arr2,arr3 )

In [21]:
!ls -l

'ls' is not recognized as an internal or external command,
operable program or batch file.


In [22]:
arrs = np.load('many_arrs.npz')

In [23]:
print(type(arrs))

<class 'numpy.lib.npyio.NpzFile'>


In [24]:
arrs.files

['arr_0', 'arr_1', 'arr_2']

In [25]:
arrs['arr_0']

array([[0.12872838, 0.19182723, 0.04377944, ..., 0.07704472, 0.20648929,
        0.45297069],
       [0.14853244, 0.78335046, 0.27512321, ..., 0.54171595, 0.57375067,
        0.57904099],
       [0.23849773, 0.27335901, 0.25609594, ..., 0.00562758, 0.29051547,
        0.23753739],
       ...,
       [0.15242957, 0.0452523 , 0.22550102, ..., 0.75263081, 0.64964346,
        0.6398895 ],
       [0.69753191, 0.39585781, 0.52300444, ..., 0.05354362, 0.17219559,
        0.32355621],
       [0.33704671, 0.068106  , 0.97899429, ..., 0.04833814, 0.38437232,
        0.48082818]])

In [26]:
arrs['arr_0'].shape

(1000, 10)

In [27]:
np.savez_compressed('many_arrs_compressed', arr1, arr2, arr3)

In [28]:
!ls -lh

'ls' is not recognized as an internal or external command,
operable program or batch file.


In [29]:
arr1 = np.zeros((10000, 1000))

In [30]:
np.savez('zeros',arr1)

In [31]:
np.savez_compressed("zeros_compressed", arr1)

In [32]:
!ls -lh

'ls' is not recognized as an internal or external command,
operable program or batch file.
