## Stats with NumPy

In [1]:
import numpy as np

In [2]:
arr = np.random.rand(100000, )

In [3]:
np.amin(arr)

4.955882660584443e-06

In [4]:
np.amax(arr)

0.9999845667684671

In [5]:
np.mean(arr)

0.5018551776803174

In [6]:
np.var(arr)

0.08343753823838213

In [7]:
np.std(arr)

0.28885556639674115

In [8]:
np.median(arr)

0.5039566016426079

In [9]:
np.percentile(arr, 50)

0.5039566016426079

In [10]:
np.percentile(arr, 10)

0.10055257384075066

In [11]:
np.percentile(arr, 90)

0.9012246042263904

In [12]:
%%time
iqr = np.percentile(arr, 75) - np.percentile(arr, 25)

Wall time: 4.01 ms


In [13]:
print(iqr)

0.5002906771317953


In [14]:
%%time
quartiles = np.percentile(arr, [25, 75])
iqr = quartiles[1] - quartiles[0]

Wall time: 0 ns


In [15]:
print(quartiles)

[0.25141762 0.7517083 ]


In [16]:
print(iqr)

0.5002906771317953


In [17]:
(arr - np.mean(arr))/ np.std(arr)

array([ 0.29092525, -1.58971382,  0.74366841, ..., -1.04973483,
       -0.08913421,  0.33722325])

In [18]:
np.histogram(arr)

(array([ 9937,  9917,  9981,  9860,  9881, 10018, 10215, 10149,  9914,
        10128], dtype=int64),
 array([4.95588266e-06, 1.00002917e-01, 2.00000878e-01, 2.99998839e-01,
        3.99996800e-01, 4.99994761e-01, 5.99992722e-01, 6.99990684e-01,
        7.99988645e-01, 8.99986606e-01, 9.99984567e-01]))

In [19]:
np.histogram(arr, bins=5)

(array([19854, 19841, 19899, 20364, 20042], dtype=int64),
 array([4.95588266e-06, 2.00000878e-01, 3.99996800e-01, 5.99992722e-01,
        7.99988645e-01, 9.99984567e-01]))

In [20]:
np.histogram(arr, bins=[0, 0.25, .50, .75, 1.0])

(array([24866, 24712, 25235, 25187], dtype=int64),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]))

In [21]:
bins = [0,0.25, 0.50, 0.75, 1.0]

In [22]:
np.digitize(arr, bins)

array([3, 1, 3, ..., 1, 2, 3], dtype=int64)

In [23]:
arr1= np.random.randint(0, 10, (10))

In [24]:
arr1

array([5, 0, 0, 5, 2, 7, 2, 2, 3, 3])

In [25]:
bins = [0, 6, 10]

In [26]:
np.digitize(arr1, bins)

array([1, 1, 1, 1, 1, 2, 1, 1, 1, 1], dtype=int64)

In [27]:
np.digitize(arr1, bins, right=True)

array([1, 0, 0, 1, 1, 2, 1, 1, 1, 1], dtype=int64)

In [28]:
arr1 = np.random.randint(50, 80, 100) #weight

In [29]:
arr2 = np.random.randint(150, 185, 100)  # heights

In [30]:
arr3 = np.random.randint(17, 22, 100)   #age

In [31]:
np.concatenate((arr1,arr2,arr3)).shape

(300,)

In [32]:
np.vstack((arr1, arr2, arr3)).shape

(3, 100)

In [33]:
arr2d = np.vstack((arr1, arr2, arr3))

In [34]:
np.amin(arr2d, axis=1 )

array([ 50, 150,  17])

In [35]:
np.amax(arr2d, axis=1 )

array([ 79, 184,  21])

In [36]:
np.mean(arr2d, axis=1 )

array([ 64.16, 167.56,  19.08])