## Broadcasting 

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(6)

In [3]:
arr1.shape

(6,)

In [4]:
arr1

array([0, 1, 2, 3, 4, 5])

In [5]:
arr1 = arr1.reshape((3, 2))

In [6]:
arr1.shape

(3, 2)

In [7]:
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [8]:
arr2 = np.arange(6).reshape((3, 2))

In [9]:
arr2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [10]:
 arr1 + arr2

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [11]:
arr2[0]

array([0, 1])

In [12]:
arr2[0].reshape((1, 2))

array([[0, 1]])

In [13]:
arr1 + arr2[0].reshape((1, 2))    # (3, 2) + (1, 2)

array([[0, 2],
       [2, 4],
       [4, 6]])

In [14]:
arr2[:, 0]

array([0, 2, 4])

In [15]:
arr2[:, 0].reshape((3, 1))

array([[0],
       [2],
       [4]])

In [16]:
arr1 + arr2[:, 0].reshape((3, 1))    # (3, 2) + (3, 1)

array([[0, 1],
       [4, 5],
       [8, 9]])

In [17]:
arr1 + 1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
arr1 = np.arange(24).reshape(2, 3, 4)

In [19]:
arr1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [20]:
arr2 = np.ones((1, 4))

In [21]:
arr2

array([[1., 1., 1., 1.]])

In [22]:
arr1 + arr2     # (2, 3, 4) + (1, 4)

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]],

       [[13., 14., 15., 16.],
        [17., 18., 19., 20.],
        [21., 22., 23., 24.]]])

In [23]:
arr1 = np.arange(4)

In [24]:
arr2 = np.arange(5)

In [25]:
print(arr1.shape, arr2.shape)

(4,) (5,)


In [26]:
# arr1 + arr2

In [27]:
arr1.reshape(4, 1) + arr2     # (4,1 ) + (5)

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [28]:
arr = np.random.rand(3, 3)

In [29]:
arr

array([[0.35864401, 0.78508346, 0.04963616],
       [0.35435575, 0.67933232, 0.70335834],
       [0.03261208, 0.47663709, 0.43731252]])

In [30]:
arr.T

array([[0.35864401, 0.35435575, 0.03261208],
       [0.78508346, 0.67933232, 0.47663709],
       [0.04963616, 0.70335834, 0.43731252]])