In [1]:
import numpy as np

## Creating np Arrays

In [2]:
arr = np.arange(5)

In [3]:
print(arr, type(arr))

[0 1 2 3 4] <class 'numpy.ndarray'>


In [4]:
arr = np.array([0.0,2,4,6,8])

In [5]:
print(arr, type(arr))

[0. 2. 4. 6. 8.] <class 'numpy.ndarray'>


In [6]:
arr.dtype

dtype('float64')

In [7]:
arr.ndim

1

In [8]:
arr.shape

(5,)

In [9]:
arr.size

5

In [10]:
arr.itemsize

8

In [11]:
arr2d = np.array([
                  [1, 2, 3],
                  [4, 5, 6]
])

In [12]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
arr2d.ndim

2

In [14]:
arr2d.shape

(2, 3)

In [15]:
arr2d.size

6

In [16]:
arr3d = np.array([
                  [ 
                   [1, 2, 3],
                   [4, 5, 6]
                  ],
                  [
                   [7, 8, 9],
                   [10, 11, 12]
                  ]
])

In [17]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [18]:
arr3d.shape

(2, 2, 3)

In [19]:
arr3d.ndim

3

In [20]:
arr3d.size

12

In [21]:
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [22]:
1729 * np.ones((2, 3, 4))

array([[[1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.]],

       [[1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.]]])

In [23]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [24]:
np.random.randn(2, 3)

array([[ 0.94874654, -1.21882941,  1.13633908],
       [-0.9578539 ,  0.77902004,  0.60976943]])

In [25]:
np.random.rand(2, 3)      #normal distribution

array([[0.73336363, 0.48389042, 0.55266362],
       [0.14558828, 0.478907  , 0.93019773]])

In [26]:
np.random.rand(10, 1)    #uniform distribution

array([[0.63598455],
       [0.12471873],
       [0.48615632],
       [0.83389173],
       [0.06228355],
       [0.4033499 ],
       [0.96311921],
       [0.44640357],
       [0.24219129],
       [0.36186913]])

In [27]:
np.random.randint(0, 100, 20)

array([34, 29, 69, 16, 59, 85, 98, 41, 57, 82,  6, 65,  8, 64, 97, 16, 11,
       46, 95,  1])

In [28]:
np.random.randint(0, 100, (2, 3))

array([[90, 60, 89],
       [59, 99, 93]])

In [29]:
np.arange(7, 70, 7)

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63])

In [30]:
np.linspace(7, 70, 10)

array([ 7., 14., 21., 28., 35., 42., 49., 56., 63., 70.])

In [31]:
np.array([True, False, True, True])

array([ True, False,  True,  True])

In [32]:
str_arr = np.array(['1.4', '2.1', '1.1'])   #U3 unicode of length three

In [33]:
arr = np.array(str_arr, dtype='float')

In [34]:
arr

array([1.4, 2.1, 1.1])