In [1]:
import numpy as np

## Indexing

In [2]:
arr3d = np.array([ 
                  [ 
                   [1, 2, 3],
                   [4, 5, 6]
                  ],
                  [
                   [7, 8, 9],
                   [10, 11, 12]
                  ]
])

In [3]:
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [4]:
arr3d[0, 0 , 0]

1

In [5]:
arr3d[1, 0, 2]

9

In [6]:
i = 1
j = 0
k =2
arr3d[i, j, k]

9

In [7]:
arr3d[0, :, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr3d[1, :, :]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [9]:
arr3d[:,1,:]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [10]:
arr3d[:, :, 0:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [11]:
arr3d % 2 == 0

array([[[False,  True, False],
        [ True, False,  True]],

       [[False,  True, False],
        [ True, False,  True]]])

In [12]:
arr3d[arr3d % 2 == 0]

array([ 2,  4,  6,  8, 10, 12])

In [13]:
arr3d[(arr3d % 2 == 1) & (arr3d > 3)]

array([ 5,  7,  9, 11])

In [14]:
arr_slice = arr3d[:, :, 0:2]

In [15]:
print(type(arr_slice))

<class 'numpy.ndarray'>


In [16]:
arr_slice.ndim

3

In [17]:
arr_slice.shape

(2, 2, 2)

In [18]:
arr_slice[0, 0, 1]

2

In [19]:
arr_slice[0, 0, 0]= 1729

In [20]:
arr_slice

array([[[1729,    2],
        [   4,    5]],

       [[   7,    8],
        [  10,   11]]])

In [21]:
print(arr3d)

[[[1729    2    3]
  [   4    5    6]]

 [[   7    8    9]
  [  10   11   12]]]


In [22]:
arr_slice = np.copy(arr3d[:, :, 0:2])

In [23]:
arr_slice[0, 0, 0] = 1

In [24]:
arr_slice

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [25]:
arr3d

array([[[1729,    2,    3],
        [   4,    5,    6]],

       [[   7,    8,    9],
        [  10,   11,   12]]])

In [26]:
arr = np.random.randint(0, 10, (5))

In [27]:
arr

array([6, 0, 8, 8, 3])

In [28]:
my_indices = [1,3,4]

In [29]:
arr[my_indices]

array([0, 8, 3])